[main]
MODEL = 'ollama_chat/hf.co/lmstudio-community/DeepSeek-Coder-V2-Lite-Instruct-GGUF:Q4_K_M'
API_BASE = 'http://localhost:11434'
SYSTEM_PROMPT = "Ты ассистент продуктового аналитика. Отвечай лаконично, постарайсе уместить максимум информации в минимум текста. Необходимо дать ответ в формате числа от 0 до 10, где 0 - точно не продающий текст, а 10 - точно маркетинговый текст. В ответе только числа!"